version: '3'

services:
  # Nginx container
  webserver:
    image: ploshka/symfony-nginx:latest
    container_name: webserver
    volumes:
      - ./:/app:ro
    ports:
      - 80:80    
    networks:
      - app-network

  # PHP-fpm container
  app:
    image: ploshka/symfony-app:latest
    container_name: app
    volumes:
      - ./:/app:rw
    networks:
      - app-network
    command: dev

  # MySQL container
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0.31}
    container_name: mysql-database
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - app-network
###< doctrine/doctrine-bundle ###

networks:
  app-network:
    driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
